QUALITY: remove @ajirving's email and replace with Github account.
latex-access/latex-access pull request #15
Opened 2022-07-03 02:00 UTC by njsch

I'm pretty sure this email address no longer works and I don't know whether we have permission to use his Gmail or any other email, so this now re-directs to his Github in readme.

2022-07-03 10:01 UTC, lukaszgo1 requested changes
LGTM assuming the unnecessary change is reverted.

2022-07-03 10:01 UTC, lukaszgo1 commented on readme.md
> +The scripts also translate the current line into English speech wghich
Please revert this change.

2022-07-03 10:42 UTC, njsch commented
Closed upon request.

2022-07-03 10:45 UTC, lukaszgo1 commented
I'm afraid there is a misunderstanding here. I only asked you to restore the line 18 to its previous form.

2022-07-03 10:48 UTC, njsch commented
Oh shoot. Yep. That letter `G`. Gotcha. I'll put it back in later and submit a pr.

2022-07-03 10:50 UTC, lukaszgo1 commented
> Oh shoot. Yep. That letter `G`. Gotcha. I'll put it back in later and submit a pr.


You can just restore this branch, push the change and reopen this one.

2022-07-04 04:27 UTC, njsch commented
@lukaszgo1, try this.

2022-07-11 05:51 UTC, lukaszgo1 approved these changes

2022-07-11 05:52 UTC, merged