Add tests for translators.
latex-access/latex-access pull request #20
Opened 2023-02-26 18:02 UTC by jakubl7545

2023-02-26 21:01 UTC, lukaszgo1 commented on latex_access/nemeth.py
> +                translation="?"+transnum+"/"+transden+"#"
Please revert this change - PR's introducing tests should not touch code they test.

2023-03-04 17:17 UTC, lukaszgo1 requested changes
In general looks good. When the remarks  below are addressed this should be ready to be merged. By the way I've added some additional tests, in places where it seemed easy to increase coverage.

2023-03-04 17:17 UTC, lukaszgo1 commented on latex_access/tests/test_nemeth.py
> +        #self.assertEqual(self.braille.frac('{2x}{3y}', 0, (1, 1)), ('?2x/3y#', 8))
The correct way to disable the tests where we know the cause of the failure is to move the code to a separate test, and mark it with `@unittest.expectedFailure`. The same goes for the misspell in `UEB`. In the current state we may easily forgot to uncomment the test whenever the code is fixed.

2023-03-04 17:17 UTC, lukaszgo1 commented on latex_access/tests/test_ueb.py
> +        self.braille.lastnumber = None
In the code `lastnumber` is always set to a digit, and never to `None`, Either change this to a number, or add an explanatory comment, which clarifies why `None` is appropriate here.

2023-03-04 17:17 UTC, lukaszgo1 commented on latex_access/tests/test_ueb.py
> +        self.braille.lastnumber = None
Same here W.R.T `None` vs an int.

2023-03-05 18:56 UTC, jakubl7545 commented
@lukaszgo1 All done. Also managed to increase coverage for ueb slightly.

2023-03-05 20:12 UTC, lukaszgo1 approved these changes
LGTM. I'm going to merge this.

2023-03-05 20:12 UTC, merged