Add tests for matrix processor
latex-access/latex-access pull request #6
Opened 2022-03-20 21:27 UTC by jakubl7545

Matrix processor is a module responsible for creating matrices from a tex source and retrieving it's elements. Tests check that matrix is properly created and it's possible to retrieve single cell, row and column.

2022-03-22 18:57 UTC, lukaszgo1 requested changes
Additional tests are needed to provide full coverage for the module:
- Explicit test for the constructor which should check that instance member have default values
- test for the `initialisedStats` method
- Test which checks that `tex_init` returns the statistics provided by `initialisedStats`
- test for a malformed matrix - it should check both that error message is returned from `tex_init` and that resulting matrix object has members set to default values
- test which checks that a trailing `\\` does not result in unnecessary empty row as per this comment "        #Remove a final blank row, if it exists.  This results from a trailing \\."
- test which ensures that `tex_init` sets instance members to default values before parsing the tex source for a matrix - the easiest way would be to construct an matrix object, set instance members to some nonsensical values, parse a known string for a matrix using `tex_init` and check that members have right values.

2022-03-23 12:50 UTC, jakubl7545 commented
@lukaszgo1 I added the requested test apart from the last one which I am not sure how to create.

2022-03-24 18:05 UTC, lukaszgo1 requested changes

2022-03-24 18:05 UTC, lukaszgo1 commented on latex_access/tests/test_matrix_processor.py
> +        self.assertEqual(self.matrix.initialisedStats(), "Initialised %d by %d matrix" % (self.matrix.rows, self.matrix.columns))
Please list the rows and columns number explicitly. The fact that `initialized_stats` retrieves them by accessing `self.rows` and `self.columns` is an implementation detail which our test should not need to know about.

2022-03-24 18:05 UTC, lukaszgo1 commented on latex_access/tests/test_matrix_processor.py
> +    def test_manformed_matrix(self):
manformed -> malformed
```suggestion
    def test_malformed_matrix(self):
```

2022-03-24 18:05 UTC, lukaszgo1 commented on latex_access/tests/test_matrix_processor.py
> +        """Tests that manformed matrix is properly handled."""
```suggestion
        """Tests that malformed matrix is properly handled."""
```

2022-03-24 18:15 UTC, lukaszgo1 commented
For the last test I requested see 024eff1

2022-03-28 18:39 UTC, jakubl7545 commented on latex_access/tests/test_matrix_processor.py
> +        self.assertIn('error', self.matrix.tex_init(r'1&2\\3'))
No particular reason here but I                 modified it and included full error text to avoid confusion.

2022-03-28 19:35 UTC, lukaszgo1 approved these changes
LGTM! I'll merge this now.

2022-03-28 19:36 UTC, merged